Library/Models/Reader.cs
using System.Collections.Generic;
using System;
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
    public class Reader
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }
        public ICollection<Copy> Copies { get; set; }

    }
}

Library/Controllers/ReaderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Library.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;

namespace Library.Controllers
{
    public class ReaderController:Controller
    {
        LibraryContext db;

        public ReaderController(LibraryContext context)
        {
            db = context;
        }

        
        public async Task<IActionResult> Index(string SearchString)
        {
            IQueryable<Reader> readers = db.Readers;

            if (!string.IsNullOrEmpty(SearchString))
            {
                readers = readers.Where(r => r.Name.Contains(SearchString));
            }
            return View(await readers.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Name, BirthDate")] Reader reader)
        {
            if (ModelState.IsValid)
            {
                db.Add(reader);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reader);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reader = await db.Readers
                                .Include(r => r.Copies)
                                .FirstOrDefaultAsync(m => m.Id == id);

            if (reader == null)
            {
                return NotFound();
            }

            foreach (var book in reader.Copies)
                await db.Books.FirstOrDefaultAsync(m => m.Id == book.BookId);

            return View(reader);


        }

        [HttpPost, ActionName("Details")]
        public async Task<IActionResult> DeleteBook(int id, [Bind("Id")] Copy copy)
        {
            db.Copies.Remove(await db.Copies.FindAsync(copy.Id));

            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reader = await db.Readers.FindAsync(id);
            if (reader == null)
            {
                return NotFound();
            }
            return View(reader);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, BirthDate")] Reader reader)
        {
            if (id != reader.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(reader);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (db.Readers.Any(e => e.Id == reader.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reader);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reader = await db.Readers.FirstOrDefaultAsync(r=> r.Id == id);

            if (reader == null)
            {
                return NotFound();
            }

            return View(reader);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reader = await db.Readers.FindAsync(id);
            db.Readers.Remove(reader);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Give(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await db.Books.Include(b=>b.Copies).ToListAsync();

            var Result = new List<Book>();
            foreach (var book in books)
            {
                if (!db.Copies.Any(x => x.BookId == book.Id && x.ReaderId == id) &&  book.Copies.Count() < book.Count)
                    Result.Add(book);

            }
            return View(Result);
        }

        [HttpPost, ActionName("Give")]
        public IActionResult GiveConfirmed(int id, [Bind("Id")] Book book)
        {
            var copy = new Copy { BookId = book.Id, ReaderId = id, Issue_Date = DateTime.Now };
            db.Copies.Add(copy);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Library/Views/Reader/Create.cshtml
@model Library.Models.Reader

@{
    ViewData["Title"] = "Create";
}

<h4> Создать книгу</h4>
<form asp-controller="Reader" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"> </div>
    <div>
        <label asp-for="Name"> </label><br />
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="BirthDate"> </label><br />
        <input type="text" asp-for="BirthDate" />
        <span asp-validation-for="BirthDate" class="text-danger"></span>
    </div>
    <input type="submit" value="Сохранить" />
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Reader/Delete.cshtml
@model Library.Models.Reader

@{
    ViewData["Title"] = "Delete";
}

<h1>Уверены, что хотите удалить этого пользователя?</h1>

<div>
    <h4>Книги</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Имя
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Дата рождения
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
    </dl>
</div>
<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Удалить" class="btn btn-danger" /> |
    <a asp-controller="Reader" asp-action="Index" >Вернуться</a>
</form>

Library/Views/Reader/Details.cshtml
@model Library.Models.Reader

@{
    ViewData["Title"] = "Details";
}
<link rel="stylesheet" href="~/list.css" />
<h1>Подробности</h1>

<div>
    <h4>Читатель</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Имя
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2"> Дата рождения </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
    </dl>
</div>
    <h4> Список выданных книг </h4>
    <ul class="list">
        @foreach (var copy in Model.Copies)
        {
            <li>
                @copy.Book?.Title |
                @copy.Book?.Author |
                @copy.Issue_Date
                <form asp-controller="Reader" asp-action="Details">
                    <input type="hidden" asp-for="@copy.Id" />
                    <input type="submit" value="Убрать" />
                </form>
            </li>
        }

    </ul>
<div>
    <a asp-controller="Reader" asp-action="Give" asp-route-id="@Model.Id"> Выдать книгу </a> |
    <a asp-controller="Reader" asp-action="Edit" asp-route-id="@Model.Id">Редактировать</a> |
    <a asp-controller="Reader" asp-action="Index">Вернуться</a>
</div>

Library/Views/Reader/Edit.cshtml
@model Library.Models.Reader

@{
    ViewData["Title"] = "Edit";
}

<h4> Создать читателя</h4>
<form asp-controller="Reader" asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"> </div>
    <input type="hidden" asp-for="Id" />
    <div>
        <label asp-for="Name"> </label><br />
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="BirthDate" > </label><br />
        <input type="text" asp-for="BirthDate" />
        <span asp-validation-for="BirthDate" class="text-danger"></span>
    </div>
    <input type="submit" value="Save" /> <br />
    <a asp-controller="Reader" asp-action="Index"> Вернуться </a>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Reader/Give.cshtml
@model IEnumerable<Library.Models.Book>

@{
    ViewData["Title"] = "Give";
}

<h4> Выдача экземпляра пользователю</h4>

<table class="index">
    <thead>
        <tr>
            <th>Название</th>
            <th>Автор</th>
            <th>Артикул</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Title</td>
                <td>@book.Author</td>
                <td>@book.Vendor</td>
                <td>
                    <form asp-controller="Reader" asp-action="Give">
                        <input type="hidden" asp-for="@book.Id" />
                        <input type="submit" value="Выдать" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-controller="Reader" asp-action="Index"> Вернуться к читаелям</a>

Library/Views/Reader/Index.cshtml
@model IEnumerable<Library.Models.Reader>
@{
    Layout = "_Layout";
}

@using (Html.BeginForm())
{
    <p>
        Поиск: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}
<a asp-controller="Reader" asp-action="Create"> Создать читателя</a>
<table class="index">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Дата рождения </th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var reader in Model)
        {
            <tr>
                <td>@reader.Name</td>
                <td>@reader.BirthDate.ToString("dd:MM:yyyy")</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@reader.Id">Редактировать</a>
                    <a asp-action="Details" asp-route-id="@reader.Id">Подробнее</a>
                    <a asp-action="Delete" asp-route-id="@reader.Id">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>